---
title: "Practice Activity 9.1: Regression"
author: "Luke Thilmony"
format:
  html:
    self-contained: true
editor: visual
---

# Setup

```{r}
#| message: false
library(tidyverse)
library(broom)
```

# 9.1

```{r}
#| message: false
animal <- read_csv(here::here(
  'supporting_artifacts',
  'Learning Targets',
  'mystery_animal.csv'
))
```

## 2 Linear Regression

```{r}
diet_model <- animal |> 
  lm(
    weight_after ~ weight_before, data = _
  )

diet_model |> 
  broom::augment() |> 
  ggplot(
    mapping = aes(y = .resid, x = .fitted)
  ) +
  geom_point()


```

# 9.2 (Simulation)

### 1.

```{r}
qunif(p = 0.95, min = 1.5, max = 3.5)
```

### 2.

```{r}
qnorm(p = .1, mean = 4.6, sd = 0.8)
```

### 3.

```{r}
1-pnorm(q = 5, mean = 4.6, sd = 0.8)
```

### 4.

```{r}
1-pchisq(q = 5, df = 4)
```

### 5.

```{r}
set.seed(1)
weights <- rnorm(100, mean = 4.6, sd = 0.8)
sum(weights<4)
```

### 6.

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n = n_reed, df = 4)
  total_weight <- sum(trombones) + sum(cornets) + sum(reeds)
  
  return(total_weight)
  
}

set.seed(1957)

my_weights <- rerun(
  .n = 1000, 
  music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
) |> 
  flatten_dbl()
sum(my_weights < 4532)
```
